### ISSUE TITLE
ValueError: process may not be a generator

### ISSUE THREAD

**Issue by eirondev** [ghackenberg/factory-design-automation#6]
When I try and run example-0 I get the following error. 

  File "/home/xxxx/anaconda3/envs/gridplant/lib/python3.12/site-packages/salabim/salabim.py", line 7122, in __init__
    raise ValueError(
ValueError: process may not be a generator (contain yield statements.)
Maybe this a non yieldless model. In that case:
- add sim.yieldless(False) or
- remove all yields or
- run salabim_unyield.py

I've tried installing specific versions of salabim but all but the latest version produces error:

 'AttributeError: module 'salabim' has no attribute 'State'

**Comment by ghackenberg** [comment]
This issue should be fixed now with the latest commit.

I think, the problem was introduced with the latest versions of Salabim, which assume yieldless models by default. However, this project uses non-yieldless models, which were the default before in Salabim...
